const {
    SERP_APIKEY = '',
    EXTERNAL_API_URL = '',
    AUTH_TOKEN = '',
    COMPANY_TOKEN = '',
    CLOUDINARY_APIKEY = '',
    CLOUDINARY_APISECRET = '',
    CLOUDINARY_NAME = '',
    CLOUDINARY_PRESET = '',
} = process.env

export const config = {
    SERP_APIKEY,
    EXTERNAL_API_URL,
    AUTH_TOKEN,
    COMPANY_TOKEN,
    CLOUDINARY_APIKEY,
    CLOUDINARY_APISECRET,
    CLOUDINARY_NAME,
    CLOUDINARY_PRESET,
}
