import { Product } from '@/interfaces/product.interface'

export const tempProducts: Product[] = [
    {
        id: 36178,
        name: 'Guante Pu Flex Negro x Par Talla 9',
        slug: 'guante-pu-flex-negro-x-par-talla-9',
        date_created: '',
        date_modified: '',
        status: 'publish',
        featured: false,
        catalog_visibility: 'visible',
        description: '',
        short_description: 'Código: 6327',
        sku: '6327',
        price: '990',
        regular_price: '990',
        sale_price: '',
        date_on_sale_from: null,
        date_on_sale_to: null,
        total_sales: 0,
        manage_stock: true,
        stock_quantity: 0,
        stock_status: 'outofstock',
        low_stock_amount: 2,
        sold_individually: false,
        weight: '',
        parent_id: 0,
        reviews_allowed: false,
        purchase_note: '',
        menu_order: 0,
        downloadable: false,
        shipping_class_id: 0,
        average_rating: '0',
    },
    {
        id: 36346,
        name: 'Soldadura 6011 - 1/8 Uyustools ( Ele6108 )',
        slug: 'soldadura-6011-1-8-uyustools-ele6108',
        date_created: '',
        date_modified: '',
        status: 'publish',
        featured: false,
        catalog_visibility: 'visible',
        description: '',
        short_description: 'Código: 6370',
        sku: '6370',
        price: '3990',
        regular_price: '3990',
        sale_price: '',
        date_on_sale_from: null,
        date_on_sale_to: null,
        total_sales: 0,
        manage_stock: true,
        stock_quantity: 5,
        stock_status: 'instock',
        low_stock_amount: 2,
        sold_individually: false,
        weight: '',
        parent_id: 0,
        reviews_allowed: false,
        purchase_note: '',
        menu_order: 0,
        downloadable: false,
        shipping_class_id: 0,
        average_rating: '0',
    },
    {
        id: 36347,
        name: 'Soldadura 6011 - 3/32  Ferromat x Kilo',
        slug: 'soldadura-6011-3-32-ferromat-x-kilo',
        date_created: '',
        date_modified: '',
        status: 'publish',
        featured: false,
        catalog_visibility: 'visible',
        description: '',
        short_description: 'Código: 6371',
        sku: '6371',
        price: '3990',
        regular_price: '3990',
        sale_price: '',
        date_on_sale_from: null,
        date_on_sale_to: null,
        total_sales: 0,
        manage_stock: true,
        stock_quantity: 952,
        stock_status: 'instock',
        low_stock_amount: 2,
        sold_individually: false,
        weight: '',
        parent_id: 0,
        reviews_allowed: false,
        purchase_note: '',
        menu_order: 0,
        downloadable: false,
        shipping_class_id: 0,
        average_rating: '0',
    },
    {
        id: 36083,
        name: 'Esquinero Madera 28x28mm x 2,4mts',
        slug: 'esquinero-madera-28x28mm-x-24mts',
        date_created: '',
        date_modified: '',
        status: 'publish',
        featured: false,
        catalog_visibility: 'visible',
        description: '',
        short_description: 'Código: 6249',
        sku: '6249',
        price: '2990',
        regular_price: '2990',
        sale_price: '',
        date_on_sale_from: null,
        date_on_sale_to: null,
        total_sales: 0,
        manage_stock: true,
        stock_quantity: -14,
        stock_status: 'outofstock',
        low_stock_amount: 2,
        sold_individually: false,
        weight: '',
        parent_id: 0,
        reviews_allowed: false,
        purchase_note: '',
        menu_order: 0,
        downloadable: false,
        shipping_class_id: 0,
        average_rating: '0',
    },
    {
        id: 35904,
        name: 'Soporte Soldadura 3" Magnetica Total (tamwh25032)',
        slug: 'soporte-soldadura-3-magnetica-total-tamwh25032',
        date_created: '',
        date_modified: '',
        status: 'publish',
        featured: false,
        catalog_visibility: 'visible',
        description: '',
        short_description: 'Código: 6176',
        sku: '6176',
        price: '3990',
        regular_price: '3990',
        sale_price: '',
        date_on_sale_from: null,
        date_on_sale_to: null,
        total_sales: 0,
        manage_stock: true,
        stock_quantity: 0,
        stock_status: 'outofstock',
        low_stock_amount: 2,
        sold_individually: false,
        weight: '',
        parent_id: 0,
        reviews_allowed: false,
        purchase_note: '',
        menu_order: 0,
        downloadable: false,
        shipping_class_id: 0,
        average_rating: '0',
    },
    {
        id: 35914,
        name: 'Probador Corriente Electrico 100 A 500v Total (tht291908)',
        slug: 'probador-corriente-electrico-100-a-500v-total-tht291908',
        date_created: '',
        date_modified: '',
        status: 'publish',
        featured: false,
        catalog_visibility: 'visible',
        description: '',
        short_description: 'Código: 6186',
        sku: '6186',
        price: '1490',
        regular_price: '1490',
        sale_price: '',
        date_on_sale_from: null,
        date_on_sale_to: null,
        total_sales: 0,
        manage_stock: true,
        stock_quantity: 19,
        stock_status: 'instock',
        low_stock_amount: 2,
        sold_individually: false,
        weight: '',
        parent_id: 0,
        reviews_allowed: false,
        purchase_note: '',
        menu_order: 0,
        downloadable: false,
        shipping_class_id: 0,
        average_rating: '0',
    },
    {
        id: 34460,
        name: 'Broca Fierro Hss 8mm C/u',
        slug: 'broca-fierro-hss-8mm-c-u',
        date_created: '',
        date_modified: '',
        status: 'publish',
        featured: false,
        catalog_visibility: 'visible',
        description: '',
        short_description: 'Código: 5668',
        sku: '5668',
        price: '2190',
        regular_price: '2190',
        sale_price: '',
        date_on_sale_from: null,
        date_on_sale_to: null,
        total_sales: 0,
        manage_stock: true,
        stock_quantity: 49,
        stock_status: 'instock',
        low_stock_amount: 2,
        sold_individually: false,
        weight: '',
        parent_id: 0,
        reviews_allowed: false,
        purchase_note: '',
        menu_order: 0,
        downloadable: false,
        shipping_class_id: 0,
        average_rating: '0',
    },
    {
        id: 34463,
        name: 'Bisagra Dorada 3"x3" F2494 Ferretools',
        slug: 'bisagra-dorada-3x3-f2494-ferretools',
        date_created: '',
        date_modified: '',
        status: 'publish',
        featured: false,
        catalog_visibility: 'visible',
        description: '',
        short_description: 'Código: 5671',
        sku: '5671',
        price: '2390',
        regular_price: '2390',
        sale_price: '',
        date_on_sale_from: null,
        date_on_sale_to: null,
        total_sales: 0,
        manage_stock: true,
        stock_quantity: 7,
        stock_status: 'instock',
        low_stock_amount: 2,
        sold_individually: false,
        weight: '',
        parent_id: 0,
        reviews_allowed: false,
        purchase_note: '',
        menu_order: 0,
        downloadable: false,
        shipping_class_id: 0,
        average_rating: '0',
    },
    {
        id: 35637,
        name: 'Enchufe Volante Hembra 2p+ T 10amp Negro Ekoline',
        slug: 'enchufe-volante-hembra-2p-t-10amp-negro-ekoline',
        date_created: '',
        date_modified: '',
        status: 'publish',
        featured: false,
        catalog_visibility: 'visible',
        description: '',
        short_description: 'Código: 5660',
        sku: '5660',
        price: '3590',
        regular_price: '3590',
        sale_price: '',
        date_on_sale_from: null,
        date_on_sale_to: null,
        total_sales: 0,
        manage_stock: true,
        stock_quantity: 99,
        stock_status: 'instock',
        low_stock_amount: 2,
        sold_individually: false,
        weight: '',
        parent_id: 0,
        reviews_allowed: false,
        purchase_note: '',
        menu_order: 0,
        downloadable: false,
        shipping_class_id: 0,
        average_rating: '0',
    },
    {
        id: 30839,
        name: 'Pila Aa Duracell ( Unidad )',
        slug: 'pila-aa-duracell-unidad',
        date_created: '',
        date_modified: '',
        status: 'publish',
        featured: false,
        catalog_visibility: 'visible',
        description: '',
        short_description: 'Código: 5386',
        sku: '5386',
        price: '1190',
        regular_price: '1190',
        sale_price: '',
        date_on_sale_from: null,
        date_on_sale_to: null,
        total_sales: 0,
        manage_stock: true,
        stock_quantity: 166,
        stock_status: 'instock',
        low_stock_amount: 2,
        sold_individually: false,
        weight: '',
        parent_id: 0,
        reviews_allowed: false,
        purchase_note: '',
        menu_order: 0,
        downloadable: false,
        shipping_class_id: 0,
        average_rating: '0',
    },
    {
        id: 29510,
        name: 'Hormigon Preparado H-20 25kg Topex',
        slug: 'hormigon-preparado-h-20-25kg-topex',
        date_created: '',
        date_modified: '',
        status: 'publish',
        featured: false,
        catalog_visibility: 'visible',
        description: '',
        short_description: 'Código: 5101',
        sku: '5101',
        price: '3990',
        regular_price: '3990',
        sale_price: '',
        date_on_sale_from: null,
        date_on_sale_to: null,
        total_sales: 0,
        manage_stock: true,
        stock_quantity: -106,
        stock_status: 'outofstock',
        low_stock_amount: 2,
        sold_individually: false,
        weight: '',
        parent_id: 0,
        reviews_allowed: false,
        purchase_note: '',
        menu_order: 0,
        downloadable: false,
        shipping_class_id: 0,
        average_rating: '0',
    },
    {
        id: 29067,
        name: 'Broca Cemento 8mm (tac210801)',
        slug: 'broca-cemento-8mm-tac210801',
        date_created: '',
        date_modified: '',
        status: 'publish',
        featured: false,
        catalog_visibility: 'visible',
        description: '',
        short_description: 'Código: 4647',
        sku: '4647',
        price: '1390',
        regular_price: '1390',
        sale_price: '',
        date_on_sale_from: null,
        date_on_sale_to: null,
        total_sales: 0,
        manage_stock: true,
        stock_quantity: 2,
        stock_status: 'instock',
        low_stock_amount: 2,
        sold_individually: false,
        weight: '',
        parent_id: 0,
        reviews_allowed: false,
        purchase_note: '',
        menu_order: 0,
        downloadable: false,
        shipping_class_id: 0,
        average_rating: '0',
    },
    {
        id: 28905,
        name: 'Carretilla Concretera 90 Lts Ploma Geobosques',
        slug: 'carretilla-concretera-90-lts-ploma-geobosques',
        date_created: '',
        date_modified: '',
        status: 'publish',
        featured: false,
        catalog_visibility: 'visible',
        description:
            'La carretilla concretera de 90L es una herramienta especializada diseñada para mezclar y transportar concreto de manera eficiente. Generalmente, cuenta con un tambor giratorio que facilita la mezcla de cemento, agua y agregados, asegurando una consistencia homogénea. Su estructura robusta y ruedas grandes permiten una fácil movilidad en terrenos irregulares y obras de construcción. Ideal para proyectos de construcción, jardinería o paisajismo, es indispensable para quienes trabajan con concreto en pequeñas y medianas cantidades. Su diseño ergonómico también.',
        short_description: 'Código: 4481',
        sku: '4481',
        price: '49990',
        regular_price: '59990',
        sale_price: '49990',
        date_on_sale_from: null,
        date_on_sale_to: null,
        total_sales: 0,
        manage_stock: true,
        stock_quantity: 139,
        stock_status: 'instock',
        low_stock_amount: 2,
        sold_individually: false,
        weight: '',
        parent_id: 0,
        reviews_allowed: false,
        purchase_note: '',
        menu_order: 0,
        downloadable: false,
        shipping_class_id: 0,
        average_rating: '0',
    },
    {
        id: 27631,
        name: 'Eslinga P/carga 1500kg 25mm x 6 Mts I/trinqueta Total (thtrs2061)',
        slug: 'eslinga-p-carga-1500kg-25mm-x-6-mts-i-trinqueta-total-thtrs2061',
        date_created: '',
        date_modified: '',
        status: 'publish',
        featured: false,
        catalog_visibility: 'visible',
        description: '',
        short_description: 'Código: 3365',
        sku: '3365',
        price: '10790',
        regular_price: '10790',
        sale_price: '',
        date_on_sale_from: null,
        date_on_sale_to: null,
        total_sales: 0,
        manage_stock: true,
        stock_quantity: 6,
        stock_status: 'instock',
        low_stock_amount: 2,
        sold_individually: false,
        weight: '',
        parent_id: 0,
        reviews_allowed: false,
        purchase_note: '',
        menu_order: 0,
        downloadable: false,
        shipping_class_id: 0,
        average_rating: '0',
    },
    {
        id: 27137,
        name: 'Lija Madera N° 60 C/u',
        slug: 'lija-madera-n-60-c-u',
        date_created: '',
        date_modified: '',
        status: 'publish',
        featured: false,
        catalog_visibility: 'visible',
        description: '',
        short_description: 'Código: 2947',
        sku: '2947',
        price: '250',
        regular_price: '250',
        sale_price: '',
        date_on_sale_from: null,
        date_on_sale_to: null,
        total_sales: 0,
        manage_stock: true,
        stock_quantity: 97,
        stock_status: 'instock',
        low_stock_amount: 2,
        sold_individually: false,
        weight: '',
        parent_id: 0,
        reviews_allowed: false,
        purchase_note: '',
        menu_order: 0,
        downloadable: false,
        shipping_class_id: 0,
        average_rating: '0',
    },
    {
        id: 27096,
        name: 'Disco Desbaste 4 1/2" W-max Wurth',
        slug: 'disco-desbaste-4-1-2-w-max-wurth',
        date_created: '',
        date_modified: '',
        status: 'publish',
        featured: false,
        catalog_visibility: 'visible',
        description: '',
        short_description: 'Código: 2913',
        sku: '2913',
        price: '1400',
        regular_price: '1400',
        sale_price: '',
        date_on_sale_from: null,
        date_on_sale_to: null,
        total_sales: 0,
        manage_stock: true,
        stock_quantity: 109,
        stock_status: 'instock',
        low_stock_amount: 2,
        sold_individually: false,
        weight: '',
        parent_id: 0,
        reviews_allowed: false,
        purchase_note: '',
        menu_order: 0,
        downloadable: false,
        shipping_class_id: 0,
        average_rating: '0',
    },
    {
        id: 26636,
        name: 'Saco ( Rojo) 60x92   C/u',
        slug: 'saco-rojo-60x92-c-u',
        date_created: '',
        date_modified: '',
        status: 'publish',
        featured: false,
        catalog_visibility: 'visible',
        description: '',
        short_description: 'Código: 2522',
        sku: '2522',
        price: '700',
        regular_price: '700',
        sale_price: '',
        date_on_sale_from: null,
        date_on_sale_to: null,
        total_sales: 0,
        manage_stock: true,
        stock_quantity: 172,
        stock_status: 'instock',
        low_stock_amount: 2,
        sold_individually: false,
        weight: '',
        parent_id: 0,
        reviews_allowed: false,
        purchase_note: '',
        menu_order: 0,
        downloadable: false,
        shipping_class_id: 0,
        average_rating: '0',
    },
    {
        id: 25832,
        name: 'Espaciadores 2.0mm (crz02r)',
        slug: 'espaciadores-2-0mm-crz02r',
        date_created: '',
        date_modified: '',
        status: 'publish',
        featured: false,
        catalog_visibility: 'visible',
        description:
            'Los espaciadores 2.0mm(crz002) son una herramienta esencial para cualquier proyecto de construcción o remodelación. Están diseñados para proporcionar una separación precisa y uniforme entre materiales como azulejos, losas, piedra y más.\n\nEstos espaciadores son de alta calidad y duraderos, lo que los hace ideales para un uso prolongado. Además, su tamaño de 2.0mm garantiza un ajuste perfecto y una alineación precisa.\n\nCon este producto, puedes lograr un acabado profesional en tus proyectos, evitando la frustración de tener materiales desalineados o mal colocados. Además, los espaciadores 2.0mm(crz002) son fáciles de usar, lo que los hace ideales tanto para profesionales como para aficionados.\n\nEn Ferretería Geoconstructor de Temuco, Chile, contamos con una amplia selección de productos de construcción y herramientas de alta calidad, incluyendo los espaciadores 2.0mm(crz002). Nuestro objetivo es proporcionar a nuestros clientes los mejores productos y servicios, para ayudarles a lograr resultados impresionantes en sus proyectos de construcción. ¡Visítanos hoy mismo y descubre cómo podemos ayudarte!',
        short_description: 'Código: 1834',
        sku: '1834',
        price: '1990',
        regular_price: '1990',
        sale_price: '',
        date_on_sale_from: null,
        date_on_sale_to: null,
        total_sales: 0,
        manage_stock: true,
        stock_quantity: 42,
        stock_status: 'instock',
        low_stock_amount: 2,
        sold_individually: false,
        weight: '',
        parent_id: 0,
        reviews_allowed: false,
        purchase_note: '',
        menu_order: 0,
        downloadable: false,
        shipping_class_id: 0,
        average_rating: '0',
    },
    {
        id: 25717,
        name: 'Saco Escombro 60 x 90 Cms',
        slug: 'saco-escombro-60-x-90-cms',
        date_created: '',
        date_modified: '',
        status: 'publish',
        featured: false,
        catalog_visibility: 'visible',
        description:
            'El saco de escombro 60 x 90 cms de la Ferretería Geoconstructor en Temuco, Chile, es el aliado perfecto para la limpieza y transporte de desechos de construcción o demolición. Confeccionado con materiales de alta resistencia, este saco es capaz de soportar grandes cargas de escombros sin sufrir daños. Su tamaño de 60 x 90 cms lo hace ideal para guardar cantidades moderadas de escombros, facilitando su manejo y transporte. Además, cuenta con una amplia boca que permite un llenado rápido y eficiente. Con el saco de escombro 60 x 90 cms de la Ferretería Geoconstructor, podrás llevar a cabo tus proyectos de construcción o renovación de manera práctica y ordenada.',
        short_description: 'Código: 1730',
        sku: '1730',
        price: '890',
        regular_price: '890',
        sale_price: '',
        date_on_sale_from: null,
        date_on_sale_to: null,
        total_sales: 0,
        manage_stock: true,
        stock_quantity: 541,
        stock_status: 'instock',
        low_stock_amount: 2,
        sold_individually: false,
        weight: '',
        parent_id: 0,
        reviews_allowed: false,
        purchase_note: '',
        menu_order: 0,
        downloadable: false,
        shipping_class_id: 0,
        average_rating: '0',
    },
    {
        id: 25534,
        name: 'Broca Fierro 6mm Total C/u',
        slug: 'broca-fierro-6mm-total-c-u',
        date_created: '',
        date_modified: '',
        status: 'publish',
        featured: false,
        catalog_visibility: 'visible',
        description: '',
        short_description: 'Código: 1571',
        sku: '1571',
        price: '890',
        regular_price: '890',
        sale_price: '',
        date_on_sale_from: null,
        date_on_sale_to: null,
        total_sales: 0,
        manage_stock: true,
        stock_quantity: 12,
        stock_status: 'instock',
        low_stock_amount: 2,
        sold_individually: false,
        weight: '',
        parent_id: 0,
        reviews_allowed: false,
        purchase_note: '',
        menu_order: 0,
        downloadable: false,
        shipping_class_id: 0,
        average_rating: '0',
    },
    {
        id: 25335,
        name: 'Aceite Mezcla 2t 1 Litro (40lt) Oregon',
        slug: 'aceite-mezcla-2t-1-litro-40lt-oregon',
        date_created: '',
        date_modified: '',
        status: 'publish',
        featured: false,
        catalog_visibility: 'visible',
        description: '',
        short_description: 'Código: 1397',
        sku: '1397',
        price: '10990',
        regular_price: '10990',
        sale_price: '',
        date_on_sale_from: null,
        date_on_sale_to: null,
        total_sales: 0,
        manage_stock: true,
        stock_quantity: 18,
        stock_status: 'instock',
        low_stock_amount: 2,
        sold_individually: false,
        weight: '',
        parent_id: 0,
        reviews_allowed: false,
        purchase_note: '',
        menu_order: 0,
        downloadable: false,
        shipping_class_id: 0,
        average_rating: '0',
    },
    {
        id: 25214,
        name: 'Adhesivo Ceramica Polvo 25k Topex / Weber',
        slug: 'adhesivo-ceramica-polvo-25k-topex-weber',
        date_created: '',
        date_modified: '',
        status: 'publish',
        featured: false,
        catalog_visibility: 'visible',
        description: '',
        short_description: 'Código: 1277',
        sku: '1277',
        price: '3490',
        regular_price: '3490',
        sale_price: '',
        date_on_sale_from: null,
        date_on_sale_to: null,
        total_sales: 0,
        manage_stock: true,
        stock_quantity: 223,
        stock_status: 'instock',
        low_stock_amount: 2,
        sold_individually: false,
        weight: '',
        parent_id: 0,
        reviews_allowed: false,
        purchase_note: '',
        menu_order: 0,
        downloadable: false,
        shipping_class_id: 0,
        average_rating: '0',
    },
    {
        id: 25148,
        name: 'Aceite Cadena x Litro',
        slug: 'aceite-cadena-x-litro',
        date_created: '',
        date_modified: '',
        status: 'publish',
        featured: false,
        catalog_visibility: 'visible',
        description: '',
        short_description: 'Código: 1215',
        sku: '1215',
        price: '1690',
        regular_price: '1690',
        sale_price: '',
        date_on_sale_from: null,
        date_on_sale_to: null,
        total_sales: 0,
        manage_stock: true,
        stock_quantity: 2417,
        stock_status: 'instock',
        low_stock_amount: 2,
        sold_individually: false,
        weight: '',
        parent_id: 0,
        reviews_allowed: false,
        purchase_note: '',
        menu_order: 0,
        downloadable: false,
        shipping_class_id: 0,
        average_rating: '0',
    },
    {
        id: 25090,
        name: 'Tarugo Clavo 6x80 C/u',
        slug: 'tarugo-clavo-6x80-c-u',
        date_created: '',
        date_modified: '',
        status: 'publish',
        featured: false,
        catalog_visibility: 'visible',
        description: '',
        short_description: 'Código: 1166',
        sku: '1166',
        price: '85',
        regular_price: '85',
        sale_price: '',
        date_on_sale_from: null,
        date_on_sale_to: null,
        total_sales: 0,
        manage_stock: true,
        stock_quantity: 1887,
        stock_status: 'instock',
        low_stock_amount: 2,
        sold_individually: false,
        weight: '',
        parent_id: 0,
        reviews_allowed: false,
        purchase_note: '',
        menu_order: 0,
        downloadable: false,
        shipping_class_id: 0,
        average_rating: '0',
    },
    {
        id: 25096,
        name: 'Tornillo Hexagonal 10x2" P/aguda C/u',
        slug: 'tornillo-hexagonal-10x2-p-aguda-c-u',
        date_created: '',
        date_modified: '',
        status: 'publish',
        featured: false,
        catalog_visibility: 'visible',
        description: '',
        short_description: 'Código: 1172',
        sku: '1172',
        price: '90',
        regular_price: '90',
        sale_price: '',
        date_on_sale_from: null,
        date_on_sale_to: null,
        total_sales: 0,
        manage_stock: true,
        stock_quantity: -1600,
        stock_status: 'outofstock',
        low_stock_amount: 2,
        sold_individually: false,
        weight: '',
        parent_id: 0,
        reviews_allowed: false,
        purchase_note: '',
        menu_order: 0,
        downloadable: false,
        shipping_class_id: 0,
        average_rating: '0',
    },
    {
        id: 25076,
        name: 'Tornillo Volcanita Crs Zn 8x3" 100 Uni',
        slug: 'tornillo-volcanita-crs-zn-8x3-100-uni',
        date_created: '',
        date_modified: '',
        status: 'publish',
        featured: false,
        catalog_visibility: 'visible',
        description:
            'El tornillo volcanita CRS ZN 8x3" es un producto de alta calidad diseñado específicamente para la instalación de placas de volcanita y tableros de yeso. Este tornillo cuenta con un recubrimiento de zinc que lo protege contra la corrosión y alarga su vida útil. Su tamaño de 8x3" es ideal para fijar la volcanita de manera segura y firme. Además, este tornillo cuenta con una cabeza que facilita su instalación con un destornillador o taladro. Con el tornillo volcanita CRS ZN 8x3" de la Ferretería Geoconstructor de Temuco, obtendrá un resultado profesional y duradero en sus proyectos de construcción o remodelación.',
        short_description: 'Código: 1154',
        sku: '1154',
        price: '4000',
        regular_price: '4000',
        sale_price: '',
        date_on_sale_from: null,
        date_on_sale_to: null,
        total_sales: 100,
        manage_stock: true,
        stock_quantity: -4327,
        stock_status: 'outofstock',
        low_stock_amount: 2,
        sold_individually: false,
        weight: '',
        parent_id: 0,
        reviews_allowed: false,
        purchase_note: '',
        menu_order: 0,
        downloadable: false,
        shipping_class_id: 0,
        average_rating: '0',
    },
    {
        id: 24812,
        name: 'Perno Coche 1/4"x2" C/u',
        slug: 'perno-coche-1-4x2-c-u',
        date_created: '',
        date_modified: '',
        status: 'publish',
        featured: false,
        catalog_visibility: 'visible',
        description:
            'El perno para coche de 1/4" x 2" es un elemento esencial para la construcción y reparación de diversas estructuras metálicas. Fabricado con materiales de alta calidad, este perno garantiza la resistencia y durabilidad necesarias para soportar grandes cargas.\n\nSu tamaño de 1/4" x 2" lo hace perfecto para aplicaciones en diferentes tipos de proyectos, como ensamblaje de muebles, construcción de estanterías o armaduras metálicas. Además, su diseño permite una fácil instalación y desmontaje, brindando comodidad al usuario.\n\nEste perno para coche se destaca por su resistencia a la corrosión, lo que lo hace ideal para su uso en exteriores o en áreas expuestas a la humedad. Su acabado plateado y brillante le otorga una apariencia estética agradable.\n\nEn Ferretería Geoconstructor de Temuco, Chile, puedes encontrar este perno para coche de 1/4" x 2" de alta calidad, a precios competitivos y con entrega rápida. Confía en nosotros para conseguir los mejores productos para tus proyectos de construcción, siempre pensando en la seguridad y eficiencia.',
        short_description: 'Código: 918',
        sku: '918',
        price: '80',
        regular_price: '80',
        sale_price: '',
        date_on_sale_from: null,
        date_on_sale_to: null,
        total_sales: 0,
        manage_stock: true,
        stock_quantity: 3334,
        stock_status: 'instock',
        low_stock_amount: 2,
        sold_individually: false,
        weight: '',
        parent_id: 0,
        reviews_allowed: false,
        purchase_note: '',
        menu_order: 0,
        downloadable: false,
        shipping_class_id: 0,
        average_rating: '0',
    },
    {
        id: 24820,
        name: 'Perno Anclaje 3/8"x5" C/u',
        slug: 'perno-anclaje-3-8x5-c-u',
        date_created: '',
        date_modified: '',
        status: 'publish',
        featured: false,
        catalog_visibility: 'visible',
        description: '',
        short_description: 'Código: 925',
        sku: '925',
        price: '590',
        regular_price: '590',
        sale_price: '',
        date_on_sale_from: null,
        date_on_sale_to: null,
        total_sales: 0,
        manage_stock: true,
        stock_quantity: 1055,
        stock_status: 'instock',
        low_stock_amount: 2,
        sold_individually: false,
        weight: '',
        parent_id: 0,
        reviews_allowed: false,
        purchase_note: '',
        menu_order: 0,
        downloadable: false,
        shipping_class_id: 0,
        average_rating: '0',
    },
    {
        id: 24851,
        name: 'Aguarras Mineral Litro Dideval',
        slug: 'aguarras-mineral-litro-dideval',
        date_created: '',
        date_modified: '',
        status: 'publish',
        featured: false,
        catalog_visibility: 'visible',
        description: '',
        short_description: 'Código: 956',
        sku: '956',
        price: '2490',
        regular_price: '2490',
        sale_price: '',
        date_on_sale_from: null,
        date_on_sale_to: null,
        total_sales: 1,
        manage_stock: true,
        stock_quantity: 60,
        stock_status: 'instock',
        low_stock_amount: 2,
        sold_individually: false,
        weight: '',
        parent_id: 0,
        reviews_allowed: false,
        purchase_note: '',
        menu_order: 0,
        downloadable: false,
        shipping_class_id: 0,
        average_rating: '0',
    },
    {
        id: 24717,
        name: 'Ench. Sobrep Triple Genesis Mwd6619s0 Schneider',
        slug: 'ench-sobrep-triple-genesis-mwd6619s0-schneider',
        date_created: '',
        date_modified: '',
        status: 'publish',
        featured: false,
        catalog_visibility: 'visible',
        description: '',
        short_description: 'Código: 834',
        sku: '834',
        price: '4690',
        regular_price: '4690',
        sale_price: '',
        date_on_sale_from: null,
        date_on_sale_to: null,
        total_sales: 0,
        manage_stock: true,
        stock_quantity: 5,
        stock_status: 'instock',
        low_stock_amount: 2,
        sold_individually: false,
        weight: '',
        parent_id: 0,
        reviews_allowed: false,
        purchase_note: '',
        menu_order: 0,
        downloadable: false,
        shipping_class_id: 0,
        average_rating: '0',
    },
    {
        id: 24539,
        name: 'Antiparra Daumer L200 Claro Daumer',
        slug: 'antiparra-daumer-l200-claro-daumer',
        date_created: '',
        date_modified: '',
        status: 'publish',
        featured: false,
        catalog_visibility: 'visible',
        description: '',
        short_description: 'Código: 677',
        sku: '677',
        price: '990',
        regular_price: '990',
        sale_price: '',
        date_on_sale_from: null,
        date_on_sale_to: null,
        total_sales: 0,
        manage_stock: true,
        stock_quantity: 24,
        stock_status: 'instock',
        low_stock_amount: 2,
        sold_individually: false,
        weight: '',
        parent_id: 0,
        reviews_allowed: false,
        purchase_note: '',
        menu_order: 0,
        downloadable: false,
        shipping_class_id: 0,
        average_rating: '0',
    },
    {
        id: 24410,
        name: 'Huincha Cinta Metrica Medir 7.5mt (flg9075)',
        slug: 'huincha-cinta-metrica-medir-7-5mt-flg9075',
        date_created: '',
        date_modified: '',
        status: 'publish',
        featured: false,
        catalog_visibility: 'visible',
        description:
            'La huincha de medir FLG9075 de 7.5 metros de longitud es la herramienta perfecta para medir con precisión en cualquier proyecto de construcción o remodelación. Con un diseño resistente y duradero, esta huincha cuenta con una carcasa ergonómica antideslizante que facilita su uso y garantiza un agarre seguro. Además, su graduación clara y legible permite una lectura rápida y precisa de las medidas. Con la huincha de medir FLG9075 de 7.5 metros de largo de la Ferretería Geoconstructor de Temuco Chile, podrás llevar a cabo tus proyectos de manera eficiente y profesional. ¡No pierdas la oportunidad de adquirir esta herramienta esencial en tu kit de construcción!',
        short_description: 'Código: 566',
        sku: '566',
        price: '4989.7',
        regular_price: '4989.7',
        sale_price: '',
        date_on_sale_from: null,
        date_on_sale_to: null,
        total_sales: 0,
        manage_stock: true,
        stock_quantity: 12,
        stock_status: 'instock',
        low_stock_amount: 2,
        sold_individually: false,
        weight: '',
        parent_id: 0,
        reviews_allowed: false,
        purchase_note: '',
        menu_order: 0,
        downloadable: false,
        shipping_class_id: 0,
        average_rating: '0',
    },
    {
        id: 24317,
        name: 'Lija Fierro N° 100 C/u',
        slug: 'lija-fierro-n-100-c-u',
        date_created: '',
        date_modified: '',
        status: 'publish',
        featured: false,
        catalog_visibility: 'visible',
        description: '',
        short_description: 'Código: 482',
        sku: '482',
        price: '760',
        regular_price: '760',
        sale_price: '',
        date_on_sale_from: null,
        date_on_sale_to: null,
        total_sales: 0,
        manage_stock: true,
        stock_quantity: 80,
        stock_status: 'instock',
        low_stock_amount: 2,
        sold_individually: false,
        weight: '',
        parent_id: 0,
        reviews_allowed: false,
        purchase_note: '',
        menu_order: 0,
        downloadable: false,
        shipping_class_id: 0,
        average_rating: '0',
    },
    {
        id: 24322,
        name: 'Lija Madera N° 120 C/u',
        slug: 'lija-madera-n-120-c-u',
        date_created: '',
        date_modified: '',
        status: 'publish',
        featured: false,
        catalog_visibility: 'visible',
        description: '',
        short_description: 'Código: 487',
        sku: '487',
        price: '250',
        regular_price: '250',
        sale_price: '',
        date_on_sale_from: null,
        date_on_sale_to: null,
        total_sales: 0,
        manage_stock: true,
        stock_quantity: -578,
        stock_status: 'outofstock',
        low_stock_amount: 2,
        sold_individually: false,
        weight: '',
        parent_id: 0,
        reviews_allowed: false,
        purchase_note: '',
        menu_order: 0,
        downloadable: false,
        shipping_class_id: 0,
        average_rating: '0',
    },
    {
        id: 24231,
        name: 'Disco Traslapado Madera G-120',
        slug: 'disco-traslapado-madera-g-120',
        date_created: '',
        date_modified: '',
        status: 'publish',
        featured: false,
        catalog_visibility: 'visible',
        description: '',
        short_description: 'Código: 405',
        sku: '405',
        price: '1690',
        regular_price: '1690',
        sale_price: '',
        date_on_sale_from: null,
        date_on_sale_to: null,
        total_sales: 0,
        manage_stock: true,
        stock_quantity: 33,
        stock_status: 'instock',
        low_stock_amount: 2,
        sold_individually: false,
        weight: '',
        parent_id: 0,
        reviews_allowed: false,
        purchase_note: '',
        menu_order: 0,
        downloadable: false,
        shipping_class_id: 0,
        average_rating: '0',
    },
    {
        id: 24271,
        name: 'Flexible Agua Hi-hi 35cm',
        slug: 'flexible-agua-hi-hi-35cm',
        date_created: '',
        date_modified: '',
        status: 'publish',
        featured: false,
        catalog_visibility: 'visible',
        description: '',
        short_description: 'Código: 441',
        sku: '441',
        price: '2690',
        regular_price: '2690',
        sale_price: '',
        date_on_sale_from: null,
        date_on_sale_to: null,
        total_sales: 0,
        manage_stock: true,
        stock_quantity: 41,
        stock_status: 'instock',
        low_stock_amount: 2,
        sold_individually: false,
        weight: '',
        parent_id: 0,
        reviews_allowed: false,
        purchase_note: '',
        menu_order: 0,
        downloadable: false,
        shipping_class_id: 0,
        average_rating: '0',
    },
    {
        id: 24274,
        name: 'Teflon Agua 3/4" Taumm',
        slug: 'teflon-agua-3-4-taumm',
        date_created: '',
        date_modified: '',
        status: 'publish',
        featured: false,
        catalog_visibility: 'visible',
        description:
            'El producto TEFLON AGUA 3/4" de la marca TAUMM es un tipo de cinta de sellado fabricada con alta calidad para garantizar una óptima resistencia al agua y una perfecta hermeticidad en conexiones de tuberías de 3/4" de diámetro. Esta cinta de teflón es ideal para su uso en instalaciones de agua potable, sistemas de riego y aplicaciones industriales donde se requiera una unión hermética y duradera. Con su alta resistencia química y térmica, el TEFLON AGUA 3/4" de TAUMM es una opción confiable y duradera para prevenir fugas y mantener la integridad de las conexiones de tuberías en cualquier proyecto. Compra este producto de calidad en Ferretería Geoconstructor, tu mejor opción para herramientas y materiales de construcción en Temuco, Chile.',
        short_description: 'Código: 443',
        sku: '443',
        price: '400',
        regular_price: '400',
        sale_price: '',
        date_on_sale_from: null,
        date_on_sale_to: null,
        total_sales: 0,
        manage_stock: true,
        stock_quantity: 123,
        stock_status: 'instock',
        low_stock_amount: 2,
        sold_individually: false,
        weight: '',
        parent_id: 0,
        reviews_allowed: false,
        purchase_note: '',
        menu_order: 0,
        downloadable: false,
        shipping_class_id: 0,
        average_rating: '0',
    },
    {
        id: 24148,
        name: 'Alambre Galv N° 14 x Rollo Kilo (36mts)',
        slug: 'alambre-galv-n-14-x-rollo-kilo-36mts',
        date_created: '',
        date_modified: '',
        status: 'publish',
        featured: false,
        catalog_visibility: 'visible',
        description: '',
        short_description: 'Código: 333',
        sku: '333',
        price: '4290',
        regular_price: '4290',
        sale_price: '',
        date_on_sale_from: null,
        date_on_sale_to: null,
        total_sales: 0,
        manage_stock: true,
        stock_quantity: 74,
        stock_status: 'instock',
        low_stock_amount: 2,
        sold_individually: false,
        weight: '',
        parent_id: 0,
        reviews_allowed: false,
        purchase_note: '',
        menu_order: 0,
        downloadable: false,
        shipping_class_id: 0,
        average_rating: '0',
    },
]
